### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by nicolairobles** [mdsills/cccedict#9]
I ran the instructions you provided and got the below error on command: ` php -f index.php`

```Fatal error: Default value for parameters with a class type hint can only be NULL in .../cccedict/src/CcCedict/Parser.php on line 72```

I'm using PHP version 5.6.30.

**Comment by mdsills** [comment]
hi - currently this code requires PHP7

**Comment by nicolairobles** [comment]
@mdsills excellent. It worked. 👍
